//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int article_id { get; set; }
        public short amount { get; set; }
        public int num { get; set; }
    
        public virtual user user { get; set; }
        public virtual article article { get; set; }
    }
}
