//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_article
    {
        public int id_article { get; set; }
        public int id_bill { get; set; }
        public double amount { get; set; }
    
        public virtual article article { get; set; }
        public virtual bill bill { get; set; }
    }
}
